{
	"ActionResult": {
		"_Name": "AppUpdate"
	},
	"OnFailure": {
		"Name": "/UserMenu/Actions/GenericBannerMessage.action",
		"Properties": {
			"Animated": true,
			"Duration": 0,
			"Message": "App Update Failure {#ActionResults:AppUpdate/error}"
		}
	},
	"OnSuccess": "/UserMenu/Rules/Application/AppUpdateResult.js",
	"_Type": "Action.Type.ApplicationUpdate"
}